enable_audio_bell no
font_family hack
font_size 10
text_composition_strategy 1.5 0
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
cursor_shape block

# Copy URL to clipboard
map ctrl+shift+y kitten hints --program @

# Note: Use stardust/cassini home.nix to set this config
