# Apply changes by running: tmux source-file ~/.tmux.conf

#set-option -g default-shell /usr/bin/fish

# Prefix tip via https://www.reddit.com/r/neovim/comments/wta8k2/why_not_use_space_as_leader_key/
# and https://koenwoortman.com/tmux-prefix-ctrl-space/
set-option -g prefix2 C-Space

setw -g mode-keys vi
set -g display-time 0
set -g history-limit 99999
# Interferes with local selection & copy, but can be mitigated with Shift/Alt+select
set -g mouse on

# Scroll
# -e exits at the bottom of scroll
bind -n S-PPage copy-mode -ue

# Use Ctrl-B a to toggle mouse mode
bind-key a set mouse
# j included for faster toggling from home row
bind-key j set mouse

# Detach other attached sessions
bind-key ` attach -d

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# macOS specific settings via https://evertpot.com/osx-tmux-vim-copy-paste-clipboard/

#set -g default-command 'reattach-to-user-namespace $SHELL --login'
# Copy-paste integration setting that macOS "just works" vim needs
#set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# Setup 'v' to begin selection as in Vim
#bind-key -T vi-copy v begin-selection
#bind-key -T vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
#bind-key -T vi-copy y copy-pipe "cat >/tmp/out"

# Update default binding of `Enter` to also use copy-pipe
#unbind -T vi-copy Enter
#bind-key -T vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
#bind-key -T vi-copy Enter copy-pipe "cat >/tmp/out"

# Bind ']' to use pbpaste
#bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
